[build]
  command = ""
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
